// <auto-generated />
using System;
using BukhariAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BukhariAI.Infrastructure.Migrations
{
    [DbContext(typeof(BukhariDbContext))]
    [Migration("20260824043744_InitialLearningPersistence")]
    partial class InitialLearningPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BukhariAI.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.BookPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<bool>("UsedOcr")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "PageNumber")
                        .IsUnique();

                    b.ToTable("BookPages", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.HadithEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HadithId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourcePagesCsv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HadithId");

                    b.ToTable("HadithEvidences", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.HadithLessonPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HadithId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Point")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("HadithId");

                    b.ToTable("HadithLessonPoints", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.HadithPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HadithId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("HadithId", "PersonId")
                        .IsUnique();

                    b.ToTable("HadithPeople", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.KnownPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FirstIntroducedLessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastReferencedLessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LearningContextId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FirstIntroducedLessonId");

                    b.HasIndex("LastReferencedLessonId");

                    b.HasIndex("PersonId");

                    b.HasIndex("LearningContextId", "PersonId")
                        .IsUnique();

                    b.ToTable("KnownPeople", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.KnownTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FirstIntroducedLessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastReferencedLessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LearningContextId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("FirstIntroducedLessonId");

                    b.HasIndex("LastReferencedLessonId");

                    b.HasIndex("LearningContextId", "Term");

                    b.ToTable("KnownTerms", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.KnownTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FirstIntroducedLessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastReferencedLessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LearningContextId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FirstIntroducedLessonId");

                    b.HasIndex("LastReferencedLessonId");

                    b.HasIndex("LearningContextId", "Topic");

                    b.ToTable("KnownTopics", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EndPage")
                        .HasColumnType("int");

                    b.Property<string>("HistoricalContext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartPage")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("BookId", "StartPage", "EndPage");

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.LessonConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonConnections", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.LessonHadith", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EasyExplanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoricalContext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ScholarlyDiscussion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonHadiths", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.LessonLearningContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("LessonLearningContexts", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.LessonPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookPageId");

                    b.HasIndex("LessonId", "BookPageId")
                        .IsUnique();

                    b.ToTable("LessonPages", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.LessonPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContextDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("LessonId", "PersonId")
                        .IsUnique();

                    b.ToTable("LessonPeople", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.LessonProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UnderstandingLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("LessonProgresses", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.ReadingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EndPage")
                        .HasColumnType("int");

                    b.Property<int>("StartPage")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("ReadingSessions", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.ReviewQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("ReviewQuestions", (string)null);
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.BookPage", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.Book", "Book")
                        .WithMany("BookPages")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.HadithEvidence", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.LessonHadith", "Hadith")
                        .WithMany("Evidences")
                        .HasForeignKey("HadithId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hadith");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.HadithLessonPoint", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.LessonHadith", "Hadith")
                        .WithMany("LessonPoints")
                        .HasForeignKey("HadithId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hadith");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.HadithPerson", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.LessonHadith", "Hadith")
                        .WithMany("HadithPeople")
                        .HasForeignKey("HadithId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BukhariAI.Domain.Entities.Person", "Person")
                        .WithMany("HadithPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hadith");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.KnownPerson", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.Lesson", "FirstIntroducedLesson")
                        .WithMany()
                        .HasForeignKey("FirstIntroducedLessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BukhariAI.Domain.Entities.Lesson", "LastReferencedLesson")
                        .WithMany()
                        .HasForeignKey("LastReferencedLessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BukhariAI.Domain.Entities.LessonLearningContext", "LearningContext")
                        .WithMany("KnownPeople")
                        .HasForeignKey("LearningContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BukhariAI.Domain.Entities.Person", "Person")
                        .WithMany("KnownPersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstIntroducedLesson");

                    b.Navigation("LastReferencedLesson");

                    b.Navigation("LearningContext");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.KnownTerm", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.Lesson", "FirstIntroducedLesson")
                        .WithMany()
                        .HasForeignKey("FirstIntroducedLessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BukhariAI.Domain.Entities.Lesson", "LastReferencedLesson")
                        .WithMany()
                        .HasForeignKey("LastReferencedLessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BukhariAI.Domain.Entities.LessonLearningContext", "LearningContext")
                        .WithMany("KnownTerms")
                        .HasForeignKey("LearningContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstIntroducedLesson");

                    b.Navigation("LastReferencedLesson");

                    b.Navigation("LearningContext");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.KnownTopic", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.Lesson", "FirstIntroducedLesson")
                        .WithMany()
                        .HasForeignKey("FirstIntroducedLessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BukhariAI.Domain.Entities.Lesson", "LastReferencedLesson")
                        .WithMany()
                        .HasForeignKey("LastReferencedLessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BukhariAI.Domain.Entities.LessonLearningContext", "LearningContext")
                        .WithMany("KnownTopics")
                        .HasForeignKey("LearningContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstIntroducedLesson");

                    b.Navigation("LastReferencedLesson");

                    b.Navigation("LearningContext");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.Book", "Book")
                        .WithMany("Lessons")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.LessonConnection", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Connections")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.LessonHadith", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Hadiths")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.LessonLearningContext", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.Book", "Book")
                        .WithMany("LearningContexts")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.LessonPage", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.BookPage", "BookPage")
                        .WithMany("LessonPages")
                        .HasForeignKey("BookPageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BukhariAI.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonPages")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookPage");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.LessonPerson", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonPeople")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BukhariAI.Domain.Entities.Person", "Person")
                        .WithMany("LessonPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.LessonProgress", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.ReadingSession", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.Book", "Book")
                        .WithMany("ReadingSessions")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.ReviewQuestion", b =>
                {
                    b.HasOne("BukhariAI.Domain.Entities.Lesson", "Lesson")
                        .WithMany("ReviewQuestions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.Book", b =>
                {
                    b.Navigation("BookPages");

                    b.Navigation("LearningContexts");

                    b.Navigation("Lessons");

                    b.Navigation("ReadingSessions");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.BookPage", b =>
                {
                    b.Navigation("LessonPages");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Hadiths");

                    b.Navigation("LessonPages");

                    b.Navigation("LessonPeople");

                    b.Navigation("LessonProgresses");

                    b.Navigation("ReviewQuestions");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.LessonHadith", b =>
                {
                    b.Navigation("Evidences");

                    b.Navigation("HadithPeople");

                    b.Navigation("LessonPoints");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.LessonLearningContext", b =>
                {
                    b.Navigation("KnownPeople");

                    b.Navigation("KnownTerms");

                    b.Navigation("KnownTopics");
                });

            modelBuilder.Entity("BukhariAI.Domain.Entities.Person", b =>
                {
                    b.Navigation("HadithPeople");

                    b.Navigation("KnownPersons");

                    b.Navigation("LessonPeople");
                });
#pragma warning restore 612, 618
        }
    }
}
