using BukhariAI.Application.Quran;

namespace BukhariAI.Infrastructure.Quran;

public static class QuranDataCatalog
{
    public static readonly IReadOnlyList<SurahMeta> AllSurahs =
    [
        new() { Number = 1, Name = "الفاتحة", EnglishName = "Al-Fatiha", TotalAyat = 7, RevelationType = "مكية" },
        new() { Number = 2, Name = "البقرة", EnglishName = "Al-Baqarah", TotalAyat = 286, RevelationType = "مدنية" },
        new() { Number = 3, Name = "آل عمران", EnglishName = "Ali 'Imran", TotalAyat = 200, RevelationType = "مدنية" },
        new() { Number = 4, Name = "النساء", EnglishName = "An-Nisa", TotalAyat = 176, RevelationType = "مدنية" },
        new() { Number = 5, Name = "المائدة", EnglishName = "Al-Ma'idah", TotalAyat = 120, RevelationType = "مدنية" },
        new() { Number = 6, Name = "الأنعام", EnglishName = "Al-An'am", TotalAyat = 165, RevelationType = "مكية" },
        new() { Number = 7, Name = "الأعراف", EnglishName = "Al-A'raf", TotalAyat = 206, RevelationType = "مكية" },
        new() { Number = 8, Name = "الأنفال", EnglishName = "Al-Anfal", TotalAyat = 75, RevelationType = "مدنية" },
        new() { Number = 9, Name = "التوبة", EnglishName = "At-Tawbah", TotalAyat = 129, RevelationType = "مدنية" },
        new() { Number = 10, Name = "يونس", EnglishName = "Yunus", TotalAyat = 109, RevelationType = "مكية" },
        new() { Number = 11, Name = "هود", EnglishName = "Hud", TotalAyat = 123, RevelationType = "مكية" },
        new() { Number = 12, Name = "يوسف", EnglishName = "Yusuf", TotalAyat = 111, RevelationType = "مكية" },
        new() { Number = 13, Name = "الرعد", EnglishName = "Ar-Ra'd", TotalAyat = 43, RevelationType = "مدنية" },
        new() { Number = 14, Name = "إبراهيم", EnglishName = "Ibrahim", TotalAyat = 52, RevelationType = "مكية" },
        new() { Number = 15, Name = "الحجر", EnglishName = "Al-Hijr", TotalAyat = 99, RevelationType = "مكية" },
        new() { Number = 16, Name = "النحل", EnglishName = "An-Nahl", TotalAyat = 128, RevelationType = "مكية" },
        new() { Number = 17, Name = "الإسراء", EnglishName = "Al-Isra", TotalAyat = 111, RevelationType = "مكية" },
        new() { Number = 18, Name = "الكهف", EnglishName = "Al-Kahf", TotalAyat = 110, RevelationType = "مكية" },
        new() { Number = 19, Name = "مريم", EnglishName = "Maryam", TotalAyat = 98, RevelationType = "مكية" },
        new() { Number = 20, Name = "طه", EnglishName = "Taha", TotalAyat = 135, RevelationType = "مكية" },
        new() { Number = 21, Name = "الأنبياء", EnglishName = "Al-Anbiya", TotalAyat = 112, RevelationType = "مكية" },
        new() { Number = 22, Name = "الحج", EnglishName = "Al-Hajj", TotalAyat = 78, RevelationType = "مدنية" },
        new() { Number = 23, Name = "المؤمنون", EnglishName = "Al-Mu'minun", TotalAyat = 118, RevelationType = "مكية" },
        new() { Number = 24, Name = "النور", EnglishName = "An-Nur", TotalAyat = 64, RevelationType = "مدنية" },
        new() { Number = 25, Name = "الفرقان", EnglishName = "Al-Furqan", TotalAyat = 77, RevelationType = "مكية" },
        new() { Number = 26, Name = "الشعراء", EnglishName = "Ash-Shu'ara", TotalAyat = 227, RevelationType = "مكية" },
        new() { Number = 27, Name = "النمل", EnglishName = "An-Naml", TotalAyat = 93, RevelationType = "مكية" },
        new() { Number = 28, Name = "القصص", EnglishName = "Al-Qasas", TotalAyat = 88, RevelationType = "مكية" },
        new() { Number = 29, Name = "العنكبوت", EnglishName = "Al-'Ankabut", TotalAyat = 69, RevelationType = "مكية" },
        new() { Number = 30, Name = "الروم", EnglishName = "Ar-Rum", TotalAyat = 60, RevelationType = "مكية" },
        new() { Number = 31, Name = "لقمان", EnglishName = "Luqman", TotalAyat = 34, RevelationType = "مكية" },
        new() { Number = 32, Name = "السجدة", EnglishName = "As-Sajdah", TotalAyat = 30, RevelationType = "مكية" },
        new() { Number = 33, Name = "الأحزاب", EnglishName = "Al-Ahzab", TotalAyat = 73, RevelationType = "مدنية" },
        new() { Number = 34, Name = "سبأ", EnglishName = "Saba", TotalAyat = 54, RevelationType = "مكية" },
        new() { Number = 35, Name = "فاطر", EnglishName = "Fatir", TotalAyat = 45, RevelationType = "مكية" },
        new() { Number = 36, Name = "يس", EnglishName = "Ya-Sin", TotalAyat = 83, RevelationType = "مكية" },
        new() { Number = 37, Name = "الصافات", EnglishName = "As-Saffat", TotalAyat = 182, RevelationType = "مكية" },
        new() { Number = 38, Name = "ص", EnglishName = "Sad", TotalAyat = 88, RevelationType = "مكية" },
        new() { Number = 39, Name = "الزمر", EnglishName = "Az-Zumar", TotalAyat = 75, RevelationType = "مكية" },
        new() { Number = 40, Name = "غافر", EnglishName = "Ghafir", TotalAyat = 85, RevelationType = "مكية" },
        new() { Number = 41, Name = "فصلت", EnglishName = "Fussilat", TotalAyat = 54, RevelationType = "مكية" },
        new() { Number = 42, Name = "الشورى", EnglishName = "Ash-Shura", TotalAyat = 53, RevelationType = "مكية" },
        new() { Number = 43, Name = "الزخرف", EnglishName = "Az-Zukhruf", TotalAyat = 89, RevelationType = "مكية" },
        new() { Number = 44, Name = "الدخان", EnglishName = "Ad-Dukhan", TotalAyat = 59, RevelationType = "مكية" },
        new() { Number = 45, Name = "الجاثية", EnglishName = "Al-Jathiyah", TotalAyat = 37, RevelationType = "مكية" },
        new() { Number = 46, Name = "الأحقاف", EnglishName = "Al-Ahqaf", TotalAyat = 35, RevelationType = "مكية" },
        new() { Number = 47, Name = "محمد", EnglishName = "Muhammad", TotalAyat = 38, RevelationType = "مدنية" },
        new() { Number = 48, Name = "الفتح", EnglishName = "Al-Fath", TotalAyat = 29, RevelationType = "مدنية" },
        new() { Number = 49, Name = "الحجرات", EnglishName = "Al-Hujurat", TotalAyat = 18, RevelationType = "مدنية" },
        new() { Number = 50, Name = "ق", EnglishName = "Qaf", TotalAyat = 45, RevelationType = "مكية" },
        new() { Number = 51, Name = "الذاريات", EnglishName = "Adh-Dhariyat", TotalAyat = 60, RevelationType = "مكية" },
        new() { Number = 52, Name = "الطور", EnglishName = "At-Tur", TotalAyat = 49, RevelationType = "مكية" },
        new() { Number = 53, Name = "النجم", EnglishName = "An-Najm", TotalAyat = 62, RevelationType = "مكية" },
        new() { Number = 54, Name = "القمر", EnglishName = "Al-Qamar", TotalAyat = 55, RevelationType = "مكية" },
        new() { Number = 55, Name = "الرحمن", EnglishName = "Ar-Rahman", TotalAyat = 78, RevelationType = "مدنية" },
        new() { Number = 56, Name = "الواقعة", EnglishName = "Al-Waqi'ah", TotalAyat = 96, RevelationType = "مكية" },
        new() { Number = 57, Name = "الحديد", EnglishName = "Al-Hadid", TotalAyat = 29, RevelationType = "مدنية" },
        new() { Number = 58, Name = "المجادلة", EnglishName = "Al-Mujadila", TotalAyat = 22, RevelationType = "مدنية" },
        new() { Number = 59, Name = "الحشر", EnglishName = "Al-Hashr", TotalAyat = 24, RevelationType = "مدنية" },
        new() { Number = 60, Name = "الممتحنة", EnglishName = "Al-Mumtahanah", TotalAyat = 13, RevelationType = "مدنية" },
        new() { Number = 61, Name = "الصف", EnglishName = "As-Saff", TotalAyat = 14, RevelationType = "مدنية" },
        new() { Number = 62, Name = "الجمعة", EnglishName = "Al-Jumu'ah", TotalAyat = 11, RevelationType = "مدنية" },
        new() { Number = 63, Name = "المنافقون", EnglishName = "Al-Munafiqun", TotalAyat = 11, RevelationType = "مدنية" },
        new() { Number = 64, Name = "التغابن", EnglishName = "At-Taghabun", TotalAyat = 18, RevelationType = "مدنية" },
        new() { Number = 65, Name = "الطلاق", EnglishName = "At-Talaq", TotalAyat = 12, RevelationType = "مدنية" },
        new() { Number = 66, Name = "التحريم", EnglishName = "At-Tahrim", TotalAyat = 12, RevelationType = "مدنية" },
        new() { Number = 67, Name = "الملك", EnglishName = "Al-Mulk", TotalAyat = 30, RevelationType = "مكية" },
        new() { Number = 68, Name = "القلم", EnglishName = "Al-Qalam", TotalAyat = 52, RevelationType = "مكية" },
        new() { Number = 69, Name = "الحاقة", EnglishName = "Al-Haqqah", TotalAyat = 52, RevelationType = "مكية" },
        new() { Number = 70, Name = "المعارج", EnglishName = "Al-Ma'arij", TotalAyat = 44, RevelationType = "مكية" },
        new() { Number = 71, Name = "نوح", EnglishName = "Nuh", TotalAyat = 28, RevelationType = "مكية" },
        new() { Number = 72, Name = "الجن", EnglishName = "Al-Jinn", TotalAyat = 28, RevelationType = "مكية" },
        new() { Number = 73, Name = "المزمل", EnglishName = "Al-Muzzammil", TotalAyat = 20, RevelationType = "مكية" },
        new() { Number = 74, Name = "المدثر", EnglishName = "Al-Muddaththir", TotalAyat = 56, RevelationType = "مكية" },
        new() { Number = 75, Name = "القيامة", EnglishName = "Al-Qiyamah", TotalAyat = 40, RevelationType = "مكية" },
        new() { Number = 76, Name = "الإنسان", EnglishName = "Al-Insan", TotalAyat = 31, RevelationType = "مدنية" },
        new() { Number = 77, Name = "المرسلات", EnglishName = "Al-Mursalat", TotalAyat = 50, RevelationType = "مكية" },
        new() { Number = 78, Name = "النبأ", EnglishName = "An-Naba", TotalAyat = 40, RevelationType = "مكية" },
        new() { Number = 79, Name = "النازعات", EnglishName = "An-Nazi'at", TotalAyat = 46, RevelationType = "مكية" },
        new() { Number = 80, Name = "عبس", EnglishName = "'Abasa", TotalAyat = 42, RevelationType = "مكية" },
        new() { Number = 81, Name = "التكوير", EnglishName = "At-Takwir", TotalAyat = 29, RevelationType = "مكية" },
        new() { Number = 82, Name = "الانفطار", EnglishName = "Al-Infitar", TotalAyat = 19, RevelationType = "مكية" },
        new() { Number = 83, Name = "المطففين", EnglishName = "Al-Mutaffifin", TotalAyat = 36, RevelationType = "مكية" },
        new() { Number = 84, Name = "الانشقاق", EnglishName = "Al-Inshiqaq", TotalAyat = 25, RevelationType = "مكية" },
        new() { Number = 85, Name = "البروج", EnglishName = "Al-Buruj", TotalAyat = 22, RevelationType = "مكية" },
        new() { Number = 86, Name = "الطارق", EnglishName = "At-Tariq", TotalAyat = 17, RevelationType = "مكية" },
        new() { Number = 87, Name = "الأعلى", EnglishName = "Al-A'la", TotalAyat = 19, RevelationType = "مكية" },
        new() { Number = 88, Name = "الغاشية", EnglishName = "Al-Ghashiyah", TotalAyat = 26, RevelationType = "مكية" },
        new() { Number = 89, Name = "الفجر", EnglishName = "Al-Fajr", TotalAyat = 30, RevelationType = "مكية" },
        new() { Number = 90, Name = "البلد", EnglishName = "Al-Balad", TotalAyat = 20, RevelationType = "مكية" },
        new() { Number = 91, Name = "الشمس", EnglishName = "Ash-Shams", TotalAyat = 15, RevelationType = "مكية" },
        new() { Number = 92, Name = "الليل", EnglishName = "Al-Layl", TotalAyat = 21, RevelationType = "مكية" },
        new() { Number = 93, Name = "الضحى", EnglishName = "Ad-Duha", TotalAyat = 11, RevelationType = "مكية" },
        new() { Number = 94, Name = "الشرح", EnglishName = "Ash-Sharh", TotalAyat = 8, RevelationType = "مكية" },
        new() { Number = 95, Name = "التين", EnglishName = "At-Tin", TotalAyat = 8, RevelationType = "مكية" },
        new() { Number = 96, Name = "العلق", EnglishName = "Al-'Alaq", TotalAyat = 19, RevelationType = "مكية" },
        new() { Number = 97, Name = "القدر", EnglishName = "Al-Qadr", TotalAyat = 5, RevelationType = "مكية" },
        new() { Number = 98, Name = "البينة", EnglishName = "Al-Bayyinah", TotalAyat = 8, RevelationType = "مدنية" },
        new() { Number = 99, Name = "الزلزلة", EnglishName = "Az-Zalzalah", TotalAyat = 8, RevelationType = "مدنية" },
        new() { Number = 100, Name = "العاديات", EnglishName = "Al-'Adiyat", TotalAyat = 11, RevelationType = "مكية" },
        new() { Number = 101, Name = "القارعة", EnglishName = "Al-Qari'ah", TotalAyat = 11, RevelationType = "مكية" },
        new() { Number = 102, Name = "التكاثر", EnglishName = "At-Takathur", TotalAyat = 8, RevelationType = "مكية" },
        new() { Number = 103, Name = "العصر", EnglishName = "Al-'Asr", TotalAyat = 3, RevelationType = "مكية" },
        new() { Number = 104, Name = "الهمزة", EnglishName = "Al-Humazah", TotalAyat = 9, RevelationType = "مكية" },
        new() { Number = 105, Name = "الفيل", EnglishName = "Al-Fil", TotalAyat = 5, RevelationType = "مكية" },
        new() { Number = 106, Name = "قريش", EnglishName = "Quraysh", TotalAyat = 4, RevelationType = "مكية" },
        new() { Number = 107, Name = "الماعون", EnglishName = "Al-Ma'un", TotalAyat = 7, RevelationType = "مكية" },
        new() { Number = 108, Name = "الكوثر", EnglishName = "Al-Kawthar", TotalAyat = 3, RevelationType = "مكية" },
        new() { Number = 109, Name = "الكافرون", EnglishName = "Al-Kafirun", TotalAyat = 6, RevelationType = "مكية" },
        new() { Number = 110, Name = "النصر", EnglishName = "An-Nasr", TotalAyat = 3, RevelationType = "مدنية" },
        new() { Number = 111, Name = "المسد", EnglishName = "Al-Masad", TotalAyat = 5, RevelationType = "مكية" },
        new() { Number = 112, Name = "الإخلاص", EnglishName = "Al-Ikhlas", TotalAyat = 4, RevelationType = "مكية" },
        new() { Number = 113, Name = "الفلق", EnglishName = "Al-Falaq", TotalAyat = 5, RevelationType = "مكية" },
        new() { Number = 114, Name = "الناس", EnglishName = "An-Nas", TotalAyat = 6, RevelationType = "مكية" }
    ];

    public static SurahMeta? FindByNumber(int number) =>
        AllSurahs.FirstOrDefault(s => s.Number == number);

    public static SurahMeta? FindByName(string name)
    {
        if (string.IsNullOrWhiteSpace(name)) return null;
        string clean = name.Replace("سورة", "").Trim();
        return AllSurahs.FirstOrDefault(s => s.Name.Contains(clean, StringComparison.OrdinalIgnoreCase) ||
                                             s.EnglishName.Contains(clean, StringComparison.OrdinalIgnoreCase));
    }
}
